Documentation for docker compose push
indigo-dc/jenkins-pipeline-library pull request #102
Opened 2020-09-19 12:22 UTC by samuelbernardolip

Update documentation for using docker compose images push feature

2020-09-21 06:39 UTC, orviz requested changes

2020-09-21 06:39 UTC, orviz commented on docs/user/config_file.rst
>     | JPL_DOCKERPASS       | Sets password of Docker registry credentials                     |
Two I would just stick to one table, content is almost the same.

2020-09-21 06:39 UTC, orviz commented on docs/user/config_file.rst
> +Docker Registry: upload images
Note that this section is at the same level as `environment` and should be a subsection of it.

2020-09-21 08:49 UTC, samuelbernardolip commented on docs/user/config_file.rst
> +Docker Registry: upload images
Actually I pictured it in a different context...
Environment variables are a feature to allow the user to add dynamic named values that can change the behaviour of the running processes.
Docker Registry is another feature that comprehends an implementation capable of uploading the packages with bundled software. This can later evolve to use buildpack approach and turn this more clear than this hackish approach using environment variables to push images.
Putting this scenario, what do you think @orviz ?

2020-09-22 10:50 UTC, orviz commented on docs/user/config_file.rst
> +Docker Registry: upload images
+1 to your approach, but then I understand that the Docker Registry section should be moved outside the `Supported settings` so:
- The configuration file: config.yml
  - Supported settings
    - config
    - sqa_criteria
    - environment
    - timeout
  - Docker Registry: upload images

what do you think?

2020-09-22 11:18 UTC, samuelbernardolip commented on docs/user/config_file.rst
> +Docker Registry: upload images
+1
You're right it should be outside supported settings.

2020-09-30 18:28 UTC, samuelbernardolip commented on docs/user/config_file.rst
> +Docker Registry: upload images
@orviz  Just corrected the documentation with the proposed changes. If you agree just merge this PR.

2020-10-26 07:36 UTC, merged