Change license to LGPL
indigo-dc/jenkins-pipeline-library pull request #146
Opened 2021-04-22 09:15 UTC by samuelbernardolip

Apply a less permissive licensing for JePL adoption (fix #145 )

2021-04-28 09:01 UTC, orviz approved these changes

2021-05-11 10:29 UTC, samuelbernardolip commented
@orviz Default LGPL license provided from Github itself... I can check for a license update.

2021-05-12 10:34 UTC, davrodgon commented
Yes, I found the same, if you choose it from the ones offered from Github you don´t have version 3 of LGPL (don´t know why).
However, if you change the file yourself Github recognises version 3.
 So I think it would be more adequate using version 3, it would be more coherent with using GPL3 for others like the jpl-validator. Also, I find the text cleaner than version 2.1.

2021-05-12 10:38 UTC, davrodgon requested changes
Change to LGPL v3

2021-05-13 08:14 UTC, davrodgon approved these changes

2021-05-13 08:26 UTC, merged